name: Deploy React Vite ke VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          SSH_HOST: ${{ secrets.VPS_HOST }}

      - name: Deploy to VPS
        run: |
          ls 
          ssh -i ~/.ssh/id_rsa root@$VPS_HOST << 'EOF'
          set -e
          git config --global --add safe.directory /var/www/ambic-fe
          cd /var/www/ambic-fe
          git restore .
          git pull origin main
          npm install --legacy-peer-deps
          npm run build
          sudo systemctl restart nginx
          cd /var/www
          chmod +x ambic-fe
          systemctl restart nginx
          EOF
        env:
          SSH_HOST: ${{ secrets.VPS_HOST }}
